// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycruxtmtbrfaibpkdgcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljcnV4dG10YnJmYWlicGtkZ2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTA4MjUsImV4cCI6MjA3MzY2NjgyNX0.nDNC6qQjeJKX5HbZ2Lwz5RzhFH0iqE-FGrldsD4gpG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});